### PR TITLE
Create schematic and PCB

### PR DESCRIPTION
**Pull request by hannersb**

### CODE REVIEW

**Comment by zainahm3d** [comment]
The VCAP1 pin on the micro might need to be connected, check out the brake light board for reference.

**Comment by zainahm3d** [comment]
Take a fresh look at the LTM8074 schematic setup. Use the 5V output example in the data sheet, and make sure the caps and connections all match. You'll need larger input capacitors I believe, and the feedback pin is currently connected to ground when it should be connected to the output voltage rail.

**Comment by zainahm3d** [comment]
Currently there are devices being connected to a 3.3V rail, but a 3.3V rail doesn't exist. you'll need a linear regulator to drop the 5v to 3.3v for those devices.

**Comment by zainahm3d** [comment]
image
 The caps here should be 0.1uF not 1uF (this was an issue with the original design)

**Comment by zainahm3d** [comment]
Move the large electrolytic 12V caps closer to the voltage regulator input for clarity (c15 and c16)

**Comment by zainahm3d** [comment]
Connect the LED drive pins to pins capable of being `SPI MOSI` pins. This will make work much easier later when programming. Also you absolutely need to set these pins and the GPIOs up in the cubeMX before pulling the trigger on this board. Make sure setting those pins as SPI outputs doesn't cause any other clashing pin type issues.

**Comment by zainahm3d** [comment]
C4 should be a 0.1uF as well

**Comment by zainahm3d** [comment]
Some of the passive component values are incorrect for the LTM8074, use the data sheet to put the right ones in. 
image

**Comment by zainahm3d** [comment]
Add a tag connect for debugging, currently I don't see any way to actually program or debug the micro. See the brake light board.

**Review by izangell — APPROVED** [review]

**Pull request merged**
